/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * BsBriefInt
 */
@JsonPropertyOrder({ BsBriefInt.JSON_PROPERTY_AVG_ROUND_TRIP, BsBriefInt.JSON_PROPERTY_IP,
    BsBriefInt.JSON_PROPERTY_NAME, BsBriefInt.JSON_PROPERTY_RX_AVG_RATE, BsBriefInt.JSON_PROPERTY_TX_AVG_RATE,
    BsBriefInt.JSON_PROPERTY_TYPE, BsBriefInt.JSON_PROPERTY_STATE, BsBriefInt.JSON_PROPERTY_CONNECTION_TYPE,
    BsBriefInt.JSON_PROPERTY_ICCID, BsBriefInt.JSON_PROPERTY_IMEI, BsBriefInt.JSON_PROPERTY_IMSI,
    BsBriefInt.JSON_PROPERTY_NETWORK_OPERATOR, BsBriefInt.JSON_PROPERTY_RSSI, BsBriefInt.JSON_PROPERTY_RSCP,
    BsBriefInt.JSON_PROPERTY_EC_IO, BsBriefInt.JSON_PROPERTY_RSRP, BsBriefInt.JSON_PROPERTY_RSRQ,
    BsBriefInt.JSON_PROPERTY_SINR, BsBriefInt.JSON_PROPERTY_SSID })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
@JsonIgnoreProperties(value = "type", // ignore manually set type, it will be automatically generated by Jackson
                                      // during serialization
        allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({ @JsonSubTypes.Type(value = BsBriefIntEthernet.class, name = "ETHERNET"),
    @JsonSubTypes.Type(value = BsBriefIntCellular.class, name = "GPRS"),
    @JsonSubTypes.Type(value = BsBriefIntWlan.class, name = "WLAN"),
    @JsonSubTypes.Type(value = BsBriefIntCellular.class, name = "BsBriefIntCellular"),
    @JsonSubTypes.Type(value = BsBriefIntEthernet.class, name = "BsBriefIntEthernet"),
    @JsonSubTypes.Type(value = BsBriefIntWlan.class, name = "BsBriefIntWlan"), })

public class BsBriefInt {
  public static final String JSON_PROPERTY_AVG_ROUND_TRIP = "avgRoundTrip";
  private Integer avgRoundTrip;

  public static final String JSON_PROPERTY_IP = "ip";
  private String ip;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_RX_AVG_RATE = "rxAvgRate";
  private Integer rxAvgRate;

  public static final String JSON_PROPERTY_TX_AVG_RATE = "txAvgRate";
  private Integer txAvgRate;

  /**
   * Interface type
   */
  public enum TypeEnum {
    ETHERNET("ETHERNET"),

    GPRS("GPRS"),

    WLAN("WLAN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  protected TypeEnum type;

  public static final String JSON_PROPERTY_STATE = "state";
  private Integer state;

  /**
   * Cellular connection type
   */
  public enum ConnectionTypeEnum {
    _3G("3G"),

    _4G("4G");

    private String value;

    ConnectionTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ConnectionTypeEnum fromValue(String value) {
      for (ConnectionTypeEnum b : ConnectionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CONNECTION_TYPE = "connectionType";
  private ConnectionTypeEnum connectionType;

  public static final String JSON_PROPERTY_ICCID = "iccid";
  private String iccid;

  public static final String JSON_PROPERTY_IMEI = "imei";
  private String imei;

  public static final String JSON_PROPERTY_IMSI = "imsi";
  private String imsi;

  public static final String JSON_PROPERTY_NETWORK_OPERATOR = "networkOperator";
  private String networkOperator;

  public static final String JSON_PROPERTY_RSSI = "rssi";
  private Float rssi;

  public static final String JSON_PROPERTY_RSCP = "rscp";
  private Float rscp;

  public static final String JSON_PROPERTY_EC_IO = "ecIo";
  private Float ecIo;

  public static final String JSON_PROPERTY_RSRP = "rsrp";
  private Float rsrp;

  public static final String JSON_PROPERTY_RSRQ = "rsrq";
  private Float rsrq;

  public static final String JSON_PROPERTY_SINR = "sinr";
  private Float sinr;

  public static final String JSON_PROPERTY_SSID = "ssid";
  private String ssid;

  public BsBriefInt() {
  }

  public BsBriefInt avgRoundTrip(Integer avgRoundTrip) {

    this.avgRoundTrip = avgRoundTrip;
    return this;
  }

  /**
   * Interface average round trip in ms
   * 
   * @return avgRoundTrip
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVG_ROUND_TRIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAvgRoundTrip() {
    return avgRoundTrip;
  }

  @JsonProperty(JSON_PROPERTY_AVG_ROUND_TRIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvgRoundTrip(Integer avgRoundTrip) {
    this.avgRoundTrip = avgRoundTrip;
  }

  public BsBriefInt ip(String ip) {

    this.ip = ip;
    return this;
  }

  /**
   * Interface IP address
   * 
   * @return ip
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIp() {
    return ip;
  }

  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIp(String ip) {
    this.ip = ip;
  }

  public BsBriefInt name(String name) {

    this.name = name;
    return this;
  }

  /**
   * Interface name
   * 
   * @return name
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }

  public BsBriefInt rxAvgRate(Integer rxAvgRate) {

    this.rxAvgRate = rxAvgRate;
    return this;
  }

  /**
   * Interface Rx average bitrate (b/s)
   * 
   * @return rxAvgRate
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RX_AVG_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRxAvgRate() {
    return rxAvgRate;
  }

  @JsonProperty(JSON_PROPERTY_RX_AVG_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRxAvgRate(Integer rxAvgRate) {
    this.rxAvgRate = rxAvgRate;
  }

  public BsBriefInt txAvgRate(Integer txAvgRate) {

    this.txAvgRate = txAvgRate;
    return this;
  }

  /**
   * Interface Tx average bitrate (b/s)
   * 
   * @return txAvgRate
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TX_AVG_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTxAvgRate() {
    return txAvgRate;
  }

  @JsonProperty(JSON_PROPERTY_TX_AVG_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTxAvgRate(Integer txAvgRate) {
    this.txAvgRate = txAvgRate;
  }

  public BsBriefInt type(TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Interface type
   * 
   * @return type
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }

  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(TypeEnum type) {
    this.type = type;
  }

  public BsBriefInt state(Integer state) {

    this.state = state;
    return this;
  }

  /**
   * State for a WLAN interface: - Down / No started (5) - Up / SSID not found /
   * No sig. (4) - Up / No IP / No DHCP lease (3) - Up / Network down (2) - Up and
   * running (1) - Up / running and used (0) - Unknown because of disconnected
   * Base Station (null)
   * 
   * @return state
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getState() {
    return state;
  }

  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(Integer state) {
    this.state = state;
  }

  public BsBriefInt connectionType(ConnectionTypeEnum connectionType) {

    this.connectionType = connectionType;
    return this;
  }

  /**
   * Cellular connection type
   * 
   * @return connectionType
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONNECTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConnectionTypeEnum getConnectionType() {
    return connectionType;
  }

  @JsonProperty(JSON_PROPERTY_CONNECTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConnectionType(ConnectionTypeEnum connectionType) {
    this.connectionType = connectionType;
  }

  public BsBriefInt iccid(String iccid) {

    this.iccid = iccid;
    return this;
  }

  /**
   * ICCID of the SIM card
   * 
   * @return iccid
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ICCID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIccid() {
    return iccid;
  }

  @JsonProperty(JSON_PROPERTY_ICCID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIccid(String iccid) {
    this.iccid = iccid;
  }

  public BsBriefInt imei(String imei) {

    this.imei = imei;
    return this;
  }

  /**
   * IMEI of the Base Station
   * 
   * @return imei
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMEI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImei() {
    return imei;
  }

  @JsonProperty(JSON_PROPERTY_IMEI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImei(String imei) {
    this.imei = imei;
  }

  public BsBriefInt imsi(String imsi) {

    this.imsi = imsi;
    return this;
  }

  /**
   * IMSI of the SIM card
   * 
   * @return imsi
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMSI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImsi() {
    return imsi;
  }

  @JsonProperty(JSON_PROPERTY_IMSI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImsi(String imsi) {
    this.imsi = imsi;
  }

  public BsBriefInt networkOperator(String networkOperator) {

    this.networkOperator = networkOperator;
    return this;
  }

  /**
   * Cellular network operator
   * 
   * @return networkOperator
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NETWORK_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNetworkOperator() {
    return networkOperator;
  }

  @JsonProperty(JSON_PROPERTY_NETWORK_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetworkOperator(String networkOperator) {
    this.networkOperator = networkOperator;
  }

  public BsBriefInt rssi(Float rssi) {

    this.rssi = rssi;
    return this;
  }

  /**
   * WLAN RSSI in dBm
   * 
   * @return rssi
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RSSI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getRssi() {
    return rssi;
  }

  @JsonProperty(JSON_PROPERTY_RSSI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRssi(Float rssi) {
    this.rssi = rssi;
  }

  public BsBriefInt rscp(Float rscp) {

    this.rscp = rscp;
    return this;
  }

  /**
   * Cellular 3G RSCP in dBm
   * 
   * @return rscp
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RSCP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getRscp() {
    return rscp;
  }

  @JsonProperty(JSON_PROPERTY_RSCP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRscp(Float rscp) {
    this.rscp = rscp;
  }

  public BsBriefInt ecIo(Float ecIo) {

    this.ecIo = ecIo;
    return this;
  }

  /**
   * Cellular 3G Ec/Io in dB
   * 
   * @return ecIo
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EC_IO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getEcIo() {
    return ecIo;
  }

  @JsonProperty(JSON_PROPERTY_EC_IO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEcIo(Float ecIo) {
    this.ecIo = ecIo;
  }

  public BsBriefInt rsrp(Float rsrp) {

    this.rsrp = rsrp;
    return this;
  }

  /**
   * Cellular 4G RSRP in dBm
   * 
   * @return rsrp
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RSRP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getRsrp() {
    return rsrp;
  }

  @JsonProperty(JSON_PROPERTY_RSRP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRsrp(Float rsrp) {
    this.rsrp = rsrp;
  }

  public BsBriefInt rsrq(Float rsrq) {

    this.rsrq = rsrq;
    return this;
  }

  /**
   * Cellular 4G RSRQ in dBm
   * 
   * @return rsrq
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RSRQ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getRsrq() {
    return rsrq;
  }

  @JsonProperty(JSON_PROPERTY_RSRQ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRsrq(Float rsrq) {
    this.rsrq = rsrq;
  }

  public BsBriefInt sinr(Float sinr) {

    this.sinr = sinr;
    return this;
  }

  /**
   * Cellular 4G SINR in dB
   * 
   * @return sinr
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SINR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getSinr() {
    return sinr;
  }

  @JsonProperty(JSON_PROPERTY_SINR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSinr(Float sinr) {
    this.sinr = sinr;
  }

  public BsBriefInt ssid(String ssid) {

    this.ssid = ssid;
    return this;
  }

  /**
   * SSID of WLAN network
   * 
   * @return ssid
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SSID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSsid() {
    return ssid;
  }

  @JsonProperty(JSON_PROPERTY_SSID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSsid(String ssid) {
    this.ssid = ssid;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsBriefInt bsBriefInt = (BsBriefInt) o;
    return Objects.equals(this.avgRoundTrip, bsBriefInt.avgRoundTrip) && Objects.equals(this.ip, bsBriefInt.ip)
            && Objects.equals(this.name, bsBriefInt.name) && Objects.equals(this.rxAvgRate, bsBriefInt.rxAvgRate)
            && Objects.equals(this.txAvgRate, bsBriefInt.txAvgRate) && Objects.equals(this.type, bsBriefInt.type)
            && Objects.equals(this.state, bsBriefInt.state)
            && Objects.equals(this.connectionType, bsBriefInt.connectionType)
            && Objects.equals(this.iccid, bsBriefInt.iccid) && Objects.equals(this.imei, bsBriefInt.imei)
            && Objects.equals(this.imsi, bsBriefInt.imsi)
            && Objects.equals(this.networkOperator, bsBriefInt.networkOperator)
            && Objects.equals(this.rssi, bsBriefInt.rssi) && Objects.equals(this.rscp, bsBriefInt.rscp)
            && Objects.equals(this.ecIo, bsBriefInt.ecIo) && Objects.equals(this.rsrp, bsBriefInt.rsrp)
            && Objects.equals(this.rsrq, bsBriefInt.rsrq) && Objects.equals(this.sinr, bsBriefInt.sinr)
            && Objects.equals(this.ssid, bsBriefInt.ssid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avgRoundTrip, ip, name, rxAvgRate, txAvgRate, type, state, connectionType, iccid, imei, imsi,
            networkOperator, rssi, rscp, ecIo, rsrp, rsrq, sinr, ssid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsBriefInt {\n");
    sb.append("    avgRoundTrip: ").append(toIndentedString(avgRoundTrip)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rxAvgRate: ").append(toIndentedString(rxAvgRate)).append("\n");
    sb.append("    txAvgRate: ").append(toIndentedString(txAvgRate)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    connectionType: ").append(toIndentedString(connectionType)).append("\n");
    sb.append("    iccid: ").append(toIndentedString(iccid)).append("\n");
    sb.append("    imei: ").append(toIndentedString(imei)).append("\n");
    sb.append("    imsi: ").append(toIndentedString(imsi)).append("\n");
    sb.append("    networkOperator: ").append(toIndentedString(networkOperator)).append("\n");
    sb.append("    rssi: ").append(toIndentedString(rssi)).append("\n");
    sb.append("    rscp: ").append(toIndentedString(rscp)).append("\n");
    sb.append("    ecIo: ").append(toIndentedString(ecIo)).append("\n");
    sb.append("    rsrp: ").append(toIndentedString(rsrp)).append("\n");
    sb.append("    rsrq: ").append(toIndentedString(rsrq)).append("\n");
    sb.append("    sinr: ").append(toIndentedString(sinr)).append("\n");
    sb.append("    ssid: ").append(toIndentedString(ssid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
