/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BsBriefAntsAntInner
 */
@JsonPropertyOrder({ BsBriefAntsAntInner.JSON_PROPERTY_CABLE_LOSS, BsBriefAntsAntInner.JSON_PROPERTY_GAIN })
@JsonTypeName("BsBrief_ants_ant_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BsBriefAntsAntInner {
  public static final String JSON_PROPERTY_CABLE_LOSS = "cableLoss";
  private Float cableLoss;

  public static final String JSON_PROPERTY_GAIN = "gain";
  private Float gain;

  public BsBriefAntsAntInner() {
  }

  public BsBriefAntsAntInner cableLoss(Float cableLoss) {

    this.cableLoss = cableLoss;
    return this;
  }

  /**
   * Cable loss in dB
   * 
   * @return cableLoss
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CABLE_LOSS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getCableLoss() {
    return cableLoss;
  }

  @JsonProperty(JSON_PROPERTY_CABLE_LOSS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCableLoss(Float cableLoss) {
    this.cableLoss = cableLoss;
  }

  public BsBriefAntsAntInner gain(Float gain) {

    this.gain = gain;
    return this;
  }

  /**
   * Antenna gain in dBi
   * 
   * @return gain
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getGain() {
    return gain;
  }

  @JsonProperty(JSON_PROPERTY_GAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGain(Float gain) {
    this.gain = gain;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsBriefAntsAntInner bsBriefAntsAntInner = (BsBriefAntsAntInner) o;
    return Objects.equals(this.cableLoss, bsBriefAntsAntInner.cableLoss)
            && Objects.equals(this.gain, bsBriefAntsAntInner.gain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cableLoss, gain);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsBriefAntsAntInner {\n");
    sb.append("    cableLoss: ").append(toIndentedString(cableLoss)).append("\n");
    sb.append("    gain: ").append(toIndentedString(gain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
