/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BsBriefAnts
 */
@JsonPropertyOrder({ BsBriefAnts.JSON_PROPERTY_ANT })
@JsonTypeName("BsBrief_ants")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BsBriefAnts {
  public static final String JSON_PROPERTY_ANT = "ant";
  private List<BsBriefAntsAntInner> ant = new ArrayList<>();

  public BsBriefAnts() {
  }

  public BsBriefAnts ant(List<BsBriefAntsAntInner> ant) {

    this.ant = ant;
    return this;
  }

  public BsBriefAnts addAntItem(BsBriefAntsAntInner antItem) {
    if (this.ant == null) {
      this.ant = new ArrayList<>();
    }
    this.ant.add(antItem);
    return this;
  }

  /**
   * Get ant
   * 
   * @return ant
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BsBriefAntsAntInner> getAnt() {
    return ant;
  }

  @JsonProperty(JSON_PROPERTY_ANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnt(List<BsBriefAntsAntInner> ant) {
    this.ant = ant;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsBriefAnts bsBriefAnts = (BsBriefAnts) o;
    return Objects.equals(this.ant, bsBriefAnts.ant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ant);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsBriefAnts {\n");
    sb.append("    ant: ").append(toIndentedString(ant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
