/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Power source of the base station. Empty until the configuration is reported
 * by the base station.
 */
@JsonPropertyOrder({ BsBriefPower.JSON_PROPERTY_BATTERY_LEVEL, BsBriefPower.JSON_PROPERTY_STATUS })
@JsonTypeName("BsBrief_power")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BsBriefPower {
  public static final String JSON_PROPERTY_BATTERY_LEVEL = "batteryLevel";
  private Integer batteryLevel;

  public static final String JSON_PROPERTY_STATUS = "status";
  private Integer status;

  public BsBriefPower() {
  }

  public BsBriefPower batteryLevel(Integer batteryLevel) {

    this.batteryLevel = batteryLevel;
    return this;
  }

  /**
   * Remaining battery level (%) when the activated power source is WIND or SOLAR.
   * 
   * @return batteryLevel
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BATTERY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBatteryLevel() {
    return batteryLevel;
  }

  @JsonProperty(JSON_PROPERTY_BATTERY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBatteryLevel(Integer batteryLevel) {
    this.batteryLevel = batteryLevel;
  }

  public BsBriefPower status(Integer status) {

    this.status = status;
    return this;
  }

  /**
   * Power source currently activated: - WIND (1) - SOLAR (2) - BATTERY (3) - POE
   * (4) - MAINS (5) - Unknown because of disconnected Base Station (null)
   * 
   * @return status
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStatus() {
    return status;
  }

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(Integer status) {
    this.status = status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsBriefPower bsBriefPower = (BsBriefPower) o;
    return Objects.equals(this.batteryLevel, bsBriefPower.batteryLevel)
            && Objects.equals(this.status, bsBriefPower.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batteryLevel, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsBriefPower {\n");
    sb.append("    batteryLevel: ").append(toIndentedString(batteryLevel)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
