/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Mounted filesystems of the base station. Empty until the configuration is
 * reported by the base station.
 */
@JsonPropertyOrder({ BsMfs.JSON_PROPERTY_MFS })
@JsonTypeName("Bs_mfs")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BsMfs {
  public static final String JSON_PROPERTY_MFS = "mfs";
  private List<BsMfsMfsInner> mfs = new ArrayList<>();

  public BsMfs() {
  }

  public BsMfs mfs(List<BsMfsMfsInner> mfs) {

    this.mfs = mfs;
    return this;
  }

  public BsMfs addMfsItem(BsMfsMfsInner mfsItem) {
    if (this.mfs == null) {
      this.mfs = new ArrayList<>();
    }
    this.mfs.add(mfsItem);
    return this;
  }

  /**
   * Get mfs
   * 
   * @return mfs
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MFS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BsMfsMfsInner> getMfs() {
    return mfs;
  }

  @JsonProperty(JSON_PROPERTY_MFS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMfs(List<BsMfsMfsInner> mfs) {
    this.mfs = mfs;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsMfs bsMfs = (BsMfs) o;
    return Objects.equals(this.mfs, bsMfs.mfs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mfs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsMfs {\n");
    sb.append("    mfs: ").append(toIndentedString(mfs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
