/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BsOwner
 */
@JsonPropertyOrder({ BsOwner.JSON_PROPERTY_I_D, BsOwner.JSON_PROPERTY_ACCESS_RIGHT, BsOwner.JSON_PROPERTY_NAME })
@JsonTypeName("Bs_owner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BsOwner {
  public static final String JSON_PROPERTY_I_D = "ID";
  private String ID;

  public static final String JSON_PROPERTY_ACCESS_RIGHT = "accessRight";
  private String accessRight;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public BsOwner() {
  }

  public BsOwner ID(String ID) {

    this.ID = ID;
    return this;
  }

  /**
   * BS owner ID
   * 
   * @return ID
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getID() {
    return ID;
  }

  @JsonProperty(JSON_PROPERTY_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setID(String ID) {
    this.ID = ID;
  }

  public BsOwner accessRight(String accessRight) {

    this.accessRight = accessRight;
    return this;
  }

  /**
   * BS owner access right: RO, RW
   * 
   * @return accessRight
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCESS_RIGHT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccessRight() {
    return accessRight;
  }

  @JsonProperty(JSON_PROPERTY_ACCESS_RIGHT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessRight(String accessRight) {
    this.accessRight = accessRight;
  }

  public BsOwner name(String name) {

    this.name = name;
    return this;
  }

  /**
   * BS owner name
   * 
   * @return name
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsOwner bsOwner = (BsOwner) o;
    return Objects.equals(this.ID, bsOwner.ID) && Objects.equals(this.accessRight, bsOwner.accessRight)
            && Objects.equals(this.name, bsOwner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, accessRight, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsOwner {\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    accessRight: ").append(toIndentedString(accessRight)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
