/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import lora.ns.actility.api.model.common.IsmBandID;
import lora.ns.actility.api.model.common.IsmBandName;

/**
 * BsProfilesBriefsInnerDefaultIsmBandsInner
 */
@JsonPropertyOrder({ BsProfilesBriefsInnerDefaultIsmBandsInner.JSON_PROPERTY_I_D,
    BsProfilesBriefsInnerDefaultIsmBandsInner.JSON_PROPERTY_NAME })
@JsonTypeName("BsProfiles_briefs_inner_defaultIsmBands_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BsProfilesBriefsInnerDefaultIsmBandsInner {
  public static final String JSON_PROPERTY_I_D = "ID";
  private IsmBandID ID;

  public static final String JSON_PROPERTY_NAME = "name";
  private IsmBandName name;

  public BsProfilesBriefsInnerDefaultIsmBandsInner() {
  }

  public BsProfilesBriefsInnerDefaultIsmBandsInner ID(IsmBandID ID) {

    this.ID = ID;
    return this;
  }

  /**
   * Get ID
   * 
   * @return ID
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IsmBandID getID() {
    return ID;
  }

  @JsonProperty(JSON_PROPERTY_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setID(IsmBandID ID) {
    this.ID = ID;
  }

  public BsProfilesBriefsInnerDefaultIsmBandsInner name(IsmBandName name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   * 
   * @return name
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IsmBandName getName() {
    return name;
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(IsmBandName name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsProfilesBriefsInnerDefaultIsmBandsInner bsProfilesBriefsInnerDefaultIsmBandsInner = (BsProfilesBriefsInnerDefaultIsmBandsInner) o;
    return Objects.equals(this.ID, bsProfilesBriefsInnerDefaultIsmBandsInner.ID)
            && Objects.equals(this.name, bsProfilesBriefsInnerDefaultIsmBandsInner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsProfilesBriefsInnerDefaultIsmBandsInner {\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
