/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import lora.ns.actility.api.model.common.Coordinates;

/**
 * The bounding box containing all base stations of the cluster: west, south,
 * east, north.
 */
@JsonPropertyOrder({ BssClustersClustersInnerBbox.JSON_PROPERTY_NORTHEAST,
    BssClustersClustersInnerBbox.JSON_PROPERTY_SOUTHWEST })
@JsonTypeName("BssClusters_clusters_inner_bbox")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BssClustersClustersInnerBbox {
  public static final String JSON_PROPERTY_NORTHEAST = "northeast";
  private Coordinates northeast;

  public static final String JSON_PROPERTY_SOUTHWEST = "southwest";
  private Coordinates southwest;

  public BssClustersClustersInnerBbox() {
  }

  public BssClustersClustersInnerBbox northeast(Coordinates northeast) {

    this.northeast = northeast;
    return this;
  }

  /**
   * Get northeast
   * 
   * @return northeast
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NORTHEAST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Coordinates getNortheast() {
    return northeast;
  }

  @JsonProperty(JSON_PROPERTY_NORTHEAST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNortheast(Coordinates northeast) {
    this.northeast = northeast;
  }

  public BssClustersClustersInnerBbox southwest(Coordinates southwest) {

    this.southwest = southwest;
    return this;
  }

  /**
   * Get southwest
   * 
   * @return southwest
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SOUTHWEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Coordinates getSouthwest() {
    return southwest;
  }

  @JsonProperty(JSON_PROPERTY_SOUTHWEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSouthwest(Coordinates southwest) {
    this.southwest = southwest;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BssClustersClustersInnerBbox bssClustersClustersInnerBbox = (BssClustersClustersInnerBbox) o;
    return Objects.equals(this.northeast, bssClustersClustersInnerBbox.northeast)
            && Objects.equals(this.southwest, bssClustersClustersInnerBbox.southwest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(northeast, southwest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BssClustersClustersInnerBbox {\n");
    sb.append("    northeast: ").append(toIndentedString(northeast)).append("\n");
    sb.append("    southwest: ").append(toIndentedString(southwest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
