/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import lora.ns.actility.api.model.common.Coordinates;

/**
 * A group a base stations close to each other.
 */
@JsonPropertyOrder({ BssClustersClustersInner.JSON_PROPERTY_COUNT, BssClustersClustersInner.JSON_PROPERTY_LOCATION,
    BssClustersClustersInner.JSON_PROPERTY_BBOX, BssClustersClustersInner.JSON_PROPERTY_ITEM })
@JsonTypeName("BssClusters_clusters_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BssClustersClustersInner {
  public static final String JSON_PROPERTY_COUNT = "count";
  private Integer count;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private Coordinates location;

  public static final String JSON_PROPERTY_BBOX = "bbox";
  private BssClustersClustersInnerBbox bbox;

  public static final String JSON_PROPERTY_ITEM = "item";
  private BsBrief item;

  public BssClustersClustersInner() {
  }

  public BssClustersClustersInner count(Integer count) {

    this.count = count;
    return this;
  }

  /**
   * Number of base stations grouped in the cluster. A cluster may contain only
   * one element. minimum: 1
   * 
   * @return count
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCount() {
    return count;
  }

  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCount(Integer count) {
    this.count = count;
  }

  public BssClustersClustersInner location(Coordinates location) {

    this.location = location;
    return this;
  }

  /**
   * Get location
   * 
   * @return location
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Coordinates getLocation() {
    return location;
  }

  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(Coordinates location) {
    this.location = location;
  }

  public BssClustersClustersInner bbox(BssClustersClustersInnerBbox bbox) {

    this.bbox = bbox;
    return this;
  }

  /**
   * Get bbox
   * 
   * @return bbox
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BBOX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BssClustersClustersInnerBbox getBbox() {
    return bbox;
  }

  @JsonProperty(JSON_PROPERTY_BBOX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBbox(BssClustersClustersInnerBbox bbox) {
    this.bbox = bbox;
  }

  public BssClustersClustersInner item(BsBrief item) {

    this.item = item;
    return this;
  }

  /**
   * Get item
   * 
   * @return item
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BsBrief getItem() {
    return item;
  }

  @JsonProperty(JSON_PROPERTY_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItem(BsBrief item) {
    this.item = item;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BssClustersClustersInner bssClustersClustersInner = (BssClustersClustersInner) o;
    return Objects.equals(this.count, bssClustersClustersInner.count)
            && Objects.equals(this.location, bssClustersClustersInner.location)
            && Objects.equals(this.bbox, bssClustersClustersInner.bbox)
            && Objects.equals(this.item, bssClustersClustersInner.item);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, location, bbox, item);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BssClustersClustersInner {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    bbox: ").append(toIndentedString(bbox)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
