/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import lora.ns.actility.api.model.basestation.BssDomainsAddedDomainsInner;
import lora.ns.actility.api.model.basestation.BssDomainsRemovedDomainsInner;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BssDomains
 */
@JsonPropertyOrder({ BssDomains.JSON_PROPERTY_ADDED_DOMAINS, BssDomains.JSON_PROPERTY_REMOVED_DOMAINS,
    BssDomains.JSON_PROPERTY_LR_R_I_DS })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BssDomains {
  public static final String JSON_PROPERTY_ADDED_DOMAINS = "addedDomains";
  private List<BssDomainsAddedDomainsInner> addedDomains = new ArrayList<>();

  public static final String JSON_PROPERTY_REMOVED_DOMAINS = "removedDomains";
  private List<BssDomainsRemovedDomainsInner> removedDomains = new ArrayList<>();

  public static final String JSON_PROPERTY_LR_R_I_DS = "LRRIDs";
  private List<String> lrRIDs = new ArrayList<>();

  public BssDomains() {
  }

  public BssDomains addedDomains(List<BssDomainsAddedDomainsInner> addedDomains) {

    this.addedDomains = addedDomains;
    return this;
  }

  public BssDomains addAddedDomainsItem(BssDomainsAddedDomainsInner addedDomainsItem) {
    if (this.addedDomains == null) {
      this.addedDomains = new ArrayList<>();
    }
    this.addedDomains.add(addedDomainsItem);
    return this;
  }

  /**
   * List of domains to add to the list of Base Stations. The list cannot contain
   * more than one domain for a given group and cannot contain a domain belonging
   * to a group used in &#x60;removedDomains&#x60; list.
   * 
   * @return addedDomains
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDED_DOMAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BssDomainsAddedDomainsInner> getAddedDomains() {
    return addedDomains;
  }

  @JsonProperty(JSON_PROPERTY_ADDED_DOMAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddedDomains(List<BssDomainsAddedDomainsInner> addedDomains) {
    this.addedDomains = addedDomains;
  }

  public BssDomains removedDomains(List<BssDomainsRemovedDomainsInner> removedDomains) {

    this.removedDomains = removedDomains;
    return this;
  }

  public BssDomains addRemovedDomainsItem(BssDomainsRemovedDomainsInner removedDomainsItem) {
    if (this.removedDomains == null) {
      this.removedDomains = new ArrayList<>();
    }
    this.removedDomains.add(removedDomainsItem);
    return this;
  }

  /**
   * List of domains to remove from the list of Base Stations. The list may
   * contain several domains for a given group but cannot contain a domain
   * belonging to a group used in &#x60;addedDomains&#x60; list.
   * 
   * @return removedDomains
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REMOVED_DOMAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BssDomainsRemovedDomainsInner> getRemovedDomains() {
    return removedDomains;
  }

  @JsonProperty(JSON_PROPERTY_REMOVED_DOMAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemovedDomains(List<BssDomainsRemovedDomainsInner> removedDomains) {
    this.removedDomains = removedDomains;
  }

  public BssDomains lrRIDs(List<String> lrRIDs) {

    this.lrRIDs = lrRIDs;
    return this;
  }

  public BssDomains addLrRIDsItem(String lrRIDsItem) {
    if (this.lrRIDs == null) {
      this.lrRIDs = new ArrayList<>();
    }
    this.lrRIDs.add(lrRIDsItem);
    return this;
  }

  /**
   * Add or remove domains on base stations matching these LRR IDs (exact match).
   * 
   * @return lrRIDs
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LR_R_I_DS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getLrRIDs() {
    return lrRIDs;
  }

  @JsonProperty(JSON_PROPERTY_LR_R_I_DS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLrRIDs(List<String> lrRIDs) {
    this.lrRIDs = lrRIDs;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BssDomains bssDomains = (BssDomains) o;
    return Objects.equals(this.addedDomains, bssDomains.addedDomains)
            && Objects.equals(this.removedDomains, bssDomains.removedDomains)
            && Objects.equals(this.lrRIDs, bssDomains.lrRIDs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addedDomains, removedDomains, lrRIDs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BssDomains {\n");
    sb.append("    addedDomains: ").append(toIndentedString(addedDomains)).append("\n");
    sb.append("    removedDomains: ").append(toIndentedString(removedDomains)).append("\n");
    sb.append("    lrRIDs: ").append(toIndentedString(lrRIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
