/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import lora.ns.actility.api.model.basestation.BsTagsBriefsInner;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BsTags
 */
@JsonPropertyOrder({ BsTags.JSON_PROPERTY_BRIEFS, BsTags.JSON_PROPERTY_MORE })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BsTags {
  public static final String JSON_PROPERTY_BRIEFS = "briefs";
  private List<BsTagsBriefsInner> briefs = new ArrayList<>();

  public static final String JSON_PROPERTY_MORE = "more";
  private Boolean more;

  public BsTags() {
  }

  public BsTags briefs(List<BsTagsBriefsInner> briefs) {

    this.briefs = briefs;
    return this;
  }

  public BsTags addBriefsItem(BsTagsBriefsInner briefsItem) {
    if (this.briefs == null) {
      this.briefs = new ArrayList<>();
    }
    this.briefs.add(briefsItem);
    return this;
  }

  /**
   * Get briefs
   * 
   * @return briefs
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BRIEFS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<BsTagsBriefsInner> getBriefs() {
    return briefs;
  }

  @JsonProperty(JSON_PROPERTY_BRIEFS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBriefs(List<BsTagsBriefsInner> briefs) {
    this.briefs = briefs;
  }

  public BsTags more(Boolean more) {

    this.more = more;
    return this;
  }

  /**
   * *TRUE when more briefs can be retrieved with an upper page index.*
   * 
   * @return more
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getMore() {
    return more;
  }

  @JsonProperty(JSON_PROPERTY_MORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMore(Boolean more) {
    this.more = more;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsTags bsTags = (BsTags) o;
    return Objects.equals(this.briefs, bsTags.briefs) && Objects.equals(this.more, bsTags.more);
  }

  @Override
  public int hashCode() {
    return Objects.hash(briefs, more);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsTags {\n");
    sb.append("    briefs: ").append(toIndentedString(briefs)).append("\n");
    sb.append("    more: ").append(toIndentedString(more)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
