/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BsTagsBriefsInner
 */
@JsonPropertyOrder({ BsTagsBriefsInner.JSON_PROPERTY_MANAGED_NETWORK_VISIBILITY,
    BsTagsBriefsInner.JSON_PROPERTY_MULTICAST_VISIBILITY, BsTagsBriefsInner.JSON_PROPERTY_NAME,
    BsTagsBriefsInner.JSON_PROPERTY_HREF })
@JsonTypeName("BsTags_briefs_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BsTagsBriefsInner {
  public static final String JSON_PROPERTY_MANAGED_NETWORK_VISIBILITY = "managedNetworkVisibility";
  private Boolean managedNetworkVisibility;

  public static final String JSON_PROPERTY_MULTICAST_VISIBILITY = "multicastVisibility";
  private Boolean multicastVisibility;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_HREF = "href";
  private String href;

  public BsTagsBriefsInner() {
  }

  public BsTagsBriefsInner managedNetworkVisibility(Boolean managedNetworkVisibility) {

    this.managedNetworkVisibility = managedNetworkVisibility;
    return this;
  }

  /**
   * TRUE if the tag is visible for managed customer network. This parameter must
   * no longer be used: it is ignored and always set to false.
   * 
   * @return managedNetworkVisibility
   * @deprecated
   **/
  @Deprecated
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGED_NETWORK_VISIBILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManagedNetworkVisibility() {
    return managedNetworkVisibility;
  }

  @JsonProperty(JSON_PROPERTY_MANAGED_NETWORK_VISIBILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManagedNetworkVisibility(Boolean managedNetworkVisibility) {
    this.managedNetworkVisibility = managedNetworkVisibility;
  }

  public BsTagsBriefsInner multicastVisibility(Boolean multicastVisibility) {

    this.multicastVisibility = multicastVisibility;
    return this;
  }

  /**
   * TRUE if the tag is visible for multicast.
   * 
   * @return multicastVisibility
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MULTICAST_VISIBILITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getMulticastVisibility() {
    return multicastVisibility;
  }

  @JsonProperty(JSON_PROPERTY_MULTICAST_VISIBILITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMulticastVisibility(Boolean multicastVisibility) {
    this.multicastVisibility = multicastVisibility;
  }

  public BsTagsBriefsInner name(String name) {

    this.name = name;
    return this;
  }

  /**
   * Tag name
   * 
   * @return name
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }

  public BsTagsBriefsInner href(String href) {

    this.href = href;
    return this;
  }

  /**
   * Get href
   * 
   * @return href
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHref() {
    return href;
  }

  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHref(String href) {
    this.href = href;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsTagsBriefsInner bsTagsBriefsInner = (BsTagsBriefsInner) o;
    return Objects.equals(this.managedNetworkVisibility, bsTagsBriefsInner.managedNetworkVisibility)
            && Objects.equals(this.multicastVisibility, bsTagsBriefsInner.multicastVisibility)
            && Objects.equals(this.name, bsTagsBriefsInner.name) && Objects.equals(this.href, bsTagsBriefsInner.href);
  }

  @Override
  public int hashCode() {
    return Objects.hash(managedNetworkVisibility, multicastVisibility, name, href);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsTagsBriefsInner {\n");
    sb.append("    managedNetworkVisibility: ").append(toIndentedString(managedNetworkVisibility)).append("\n");
    sb.append("    multicastVisibility: ").append(toIndentedString(multicastVisibility)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
