/*
 * ThingPark things management Networks API
 * REST interface for networks management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.basestation;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BsVersion
 */
@JsonPropertyOrder({ BsVersion.JSON_PROPERTY_STATUS, BsVersion.JSON_PROPERTY_STATUS_INFO,
    BsVersion.JSON_PROPERTY_VERSION })
@JsonTypeName("Bs_version")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-31T16:08:44.630492043+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class BsVersion {
  /**
   * Version status: OUTDATED, UPTODATE, DEPRECATED
   */
  public enum StatusEnum {
    OUTDATED("OUTDATED"),

    UPTODATE("UPTODATE"),

    DEPRECATED("DEPRECATED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_STATUS_INFO = "statusInfo";
  private String statusInfo;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public BsVersion() {
  }

  public BsVersion status(StatusEnum status) {

    this.status = status;
    return this;
  }

  /**
   * Version status: OUTDATED, UPTODATE, DEPRECATED
   * 
   * @return status
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public BsVersion statusInfo(String statusInfo) {

    this.statusInfo = statusInfo;
    return this;
  }

  /**
   * Friendly version status info
   * 
   * @return statusInfo
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatusInfo() {
    return statusInfo;
  }

  @JsonProperty(JSON_PROPERTY_STATUS_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusInfo(String statusInfo) {
    this.statusInfo = statusInfo;
  }

  public BsVersion version(String version) {

    this.version = version;
    return this;
  }

  /**
   * LRR software version
   * 
   * @return version
   **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }

  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(String version) {
    this.version = version;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BsVersion bsVersion = (BsVersion) o;
    return Objects.equals(this.status, bsVersion.status) && Objects.equals(this.statusInfo, bsVersion.statusInfo)
            && Objects.equals(this.version, bsVersion.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, statusInfo, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BsVersion {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusInfo: ").append(toIndentedString(statusInfo)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
