/*
 * ThingPark things management Devices API
 * REST interface for Devices management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.appserver;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Message mode routing criteria Mandatory when mode is MIXED
 */
@JsonPropertyOrder({ AppServersRoutingProfileCellularMessageRouting.JSON_PROPERTY_SOURCE_PORT })
@JsonTypeName("AppServersRoutingProfileCellular_messageRouting")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-29T11:38:36.048437806+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class AppServersRoutingProfileCellularMessageRouting {
  public static final String JSON_PROPERTY_SOURCE_PORT = "sourcePort";
  private Integer sourcePort;

  public AppServersRoutingProfileCellularMessageRouting() {
  }

  public AppServersRoutingProfileCellularMessageRouting sourcePort(Integer sourcePort) {

    this.sourcePort = sourcePort;
    return this;
  }

  /**
   * Message mode source UDP port
   * 
   * @return sourcePort
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SOURCE_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSourcePort() {
    return sourcePort;
  }

  @JsonProperty(JSON_PROPERTY_SOURCE_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourcePort(Integer sourcePort) {
    this.sourcePort = sourcePort;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppServersRoutingProfileCellularMessageRouting appServersRoutingProfileCellularMessageRouting = (AppServersRoutingProfileCellularMessageRouting) o;
    return Objects.equals(this.sourcePort, appServersRoutingProfileCellularMessageRouting.sourcePort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourcePort);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppServersRoutingProfileCellularMessageRouting {\n");
    sb.append("    sourcePort: ").append(toIndentedString(sourcePort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
