/*
 * ThingPark things management Devices API
 * REST interface for Devices management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.appserver;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AppServersRoutingProfileLorawanSupplierAppServersInner
 */
@JsonPropertyOrder({ AppServersRoutingProfileLorawanSupplierAppServersInner.JSON_PROPERTY_I_D,
    AppServersRoutingProfileLorawanSupplierAppServersInner.JSON_PROPERTY_HREF,
    AppServersRoutingProfileLorawanSupplierAppServersInner.JSON_PROPERTY_SUPLIER_I_D })
@JsonTypeName("AppServersRoutingProfileLorawan_supplierAppServers_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-29T11:38:36.048437806+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class AppServersRoutingProfileLorawanSupplierAppServersInner {
  public static final String JSON_PROPERTY_I_D = "ID";
  private String ID;

  public static final String JSON_PROPERTY_HREF = "href";
  private String href;

  public static final String JSON_PROPERTY_SUPLIER_I_D = "suplierID";
  private String suplierID;

  public AppServersRoutingProfileLorawanSupplierAppServersInner() {
  }

  @JsonCreator
  public AppServersRoutingProfileLorawanSupplierAppServersInner(@JsonProperty(JSON_PROPERTY_HREF) String href,
          @JsonProperty(JSON_PROPERTY_SUPLIER_I_D) String suplierID) {
    this();
    this.href = href;
    this.suplierID = suplierID;
  }

  public AppServersRoutingProfileLorawanSupplierAppServersInner ID(String ID) {

    this.ID = ID;
    return this;
  }

  /**
   * Supplier Application ID
   * 
   * @return ID
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getID() {
    return ID;
  }

  @JsonProperty(JSON_PROPERTY_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setID(String ID) {
    this.ID = ID;
  }

  /**
   * Supplier Application HREF
   * 
   * @return href
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHref() {
    return href;
  }

  /**
   * Supplier ID
   * 
   * @return suplierID
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUPLIER_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSuplierID() {
    return suplierID;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppServersRoutingProfileLorawanSupplierAppServersInner appServersRoutingProfileLorawanSupplierAppServersInner = (AppServersRoutingProfileLorawanSupplierAppServersInner) o;
    return Objects.equals(this.ID, appServersRoutingProfileLorawanSupplierAppServersInner.ID)
            && Objects.equals(this.href, appServersRoutingProfileLorawanSupplierAppServersInner.href)
            && Objects.equals(this.suplierID, appServersRoutingProfileLorawanSupplierAppServersInner.suplierID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, href, suplierID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppServersRoutingProfileLorawanSupplierAppServersInner {\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    suplierID: ").append(toIndentedString(suplierID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
