/*
 * ThingPark things management Devices API
 * REST interface for Devices management. 
 *
 * The version of the OpenAPI document: 7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package lora.ns.actility.api.model.appserver;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AppServers
 */
@JsonPropertyOrder({ AppServers.JSON_PROPERTY_BRIEFS, AppServers.JSON_PROPERTY_MORE })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-29T11:38:36.048437806+02:00[Europe/Paris]", comments = "Generator version: 7.6.0")
public class AppServers {
  public static final String JSON_PROPERTY_BRIEFS = "briefs";
  private List<AppServersBriefsInner> briefs = new ArrayList<>();

  public static final String JSON_PROPERTY_MORE = "more";
  private Boolean more;

  public AppServers() {
  }

  public AppServers briefs(List<AppServersBriefsInner> briefs) {

    this.briefs = briefs;
    return this;
  }

  public AppServers addBriefsItem(AppServersBriefsInner briefsItem) {
    if (this.briefs == null) {
      this.briefs = new ArrayList<>();
    }
    this.briefs.add(briefsItem);
    return this;
  }

  /**
   * Get briefs
   * 
   * @return briefs
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BRIEFS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AppServersBriefsInner> getBriefs() {
    return briefs;
  }

  @JsonProperty(JSON_PROPERTY_BRIEFS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBriefs(List<AppServersBriefsInner> briefs) {
    this.briefs = briefs;
  }

  public AppServers more(Boolean more) {

    this.more = more;
    return this;
  }

  /**
   * &#x60;TRUE&#x60; when more briefs can be retrieved with an upper page index.
   * 
   * @return more
   **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getMore() {
    return more;
  }

  @JsonProperty(JSON_PROPERTY_MORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMore(Boolean more) {
    this.more = more;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppServers appServers = (AppServers) o;
    return Objects.equals(this.briefs, appServers.briefs) && Objects.equals(this.more, appServers.more);
  }

  @Override
  public int hashCode() {
    return Objects.hash(briefs, more);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppServers {\n");
    sb.append("    briefs: ").append(toIndentedString(briefs)).append("\n");
    sb.append("    more: ").append(toIndentedString(more)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
